$cwd = $PSScriptRoot;
$inputs = "$cwd/config/inputs.json";
$output = "$cwd/Generated/CreateInputs.cpp";

$inputs = Get-Content $inputs -Raw 
$inputs = ConvertFrom-Json $inputs

$lines = "";
$pinId = 0;

foreach ($input in $inputs) {
    $pinCount = $input.pins.Length 
    if ($input.type -eq "button") {
        if($pinCount -ne 1) {
            Write-Error "Invalid pin count, expected 1 got $pinCount";
            continue;
        }
        $pin = [int]$input.pins[0]
        $lines += "        inputs.push_back(etl::unique_ptr<Input>(new Button($pinId, $pin)));`n"
    }
    elseif ($input.type -eq "encoder") {
        if($pinCount -ne 2) {
            Write-Error "Invalid pin count, expected 2 got $pinCount";
            continue;
        }
        $pinA = [int]$input.pins[0]
        $pinB = [int]$input.pins[1]
        $lines += "        inputs.push_back(etl::unique_ptr<Input>(new Encoder($pinId, $pinA, $pinB)));`n"
    }
    elseif ($input.type -eq "encoderWithButton") {
        if($pinCount -ne 3) {
            Write-Error "Invalid pin count, expected 3 got $pinCount";
            continue;
        }

        $pinA = [int]$input.pins[0]
        $pinB = [int]$input.pins[1]
        $pinButton = [int]$input.pins[2]
        $lines += "        inputs.push_back(etl::unique_ptr<Input>(new EncoderWithButton($pinId, $pinA, $pinB, $pinButton)));`n"
    }

    $pinId += 1;
}

$content = @"
// THIS FILE IS AUTOGENERATED, CHANGES MADE TO IT WILL BE LOST

#include "../IO/Input/CreateInputs.h"


namespace IO::Input {

    etl::vector<etl::unique_ptr<Input>, 256> CreateInputs()
    {
        etl::vector<etl::unique_ptr<Input>, 256> inputs;

$lines

        return inputs;
    }
}

"@;

$content | Out-File -FilePath $output -Encoding utf8 -Force 

